name: Check compilation/bindings/style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          override: true
      - run: npm install
      - run: npm run ci
      - run: npm run test-ci
      - run: ./scripts/check-dirty.sh
      - run: make install
        env:
          PREFIX: /tmp
      - run: cargo test
      - run: cd ./test-npm-package && npm test; cd -
      - run: npm pack && cd .. && npm install -g ./tree-sitter-swift/tree-sitter-swift-*.tgz; cd -
