name: Create release

on:
  push:
    tags-ignore: ["*-with-generated-files"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm install
      - uses: tree-sitter/workflows/.github/workflows/release.yml@main
        with:
          attestations: true
